In [185]:
import pandas as pd
import numpy as np

In [186]:
data = np.array([["Country", "w", "t"], ["germany", 1, 2], ["france", 3, 4], ["denmark", 5, 6]])

In [187]:
#data[column, row]
df = pd.DataFrame(data=data[1:, 0:], columns=data[0, 0:])

In [188]:
df_copy = df

In [189]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [190]:
le = LabelEncoder()
df_copy["Country"] = le.fit_transform(df["Country"])

In [182]:
#df_num = ['w', 't']
#df_cat = ['Country']

In [124]:
hotEncoder = OneHotEncoder(categorical_features=[0])
df_hot = hotEncoder.fit_transform(df).toarray()

D:\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [125]:
df_hot

array([[0., 0., 1., 1., 2.],
       [0., 1., 0., 3., 4.],
       [1., 0., 0., 5., 6.]])

In [191]:
from sklearn.compose import ColumnTransformer, make_column_transformer
preprocess = make_column_transformer((OneHotEncoder(categories='auto'), ["Country"]))

In [192]:

df_cat = preprocess.fit_transform(df_copy)

In [193]:
df_cat

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [199]:
df_num = df_copy.iloc[0:, 1:].values
df_num

array([['1', '2'],
       ['3', '4'],
       ['5', '6']], dtype=object)

In [200]:
np.concatenate((df_cat,df_num), axis = 1)

array([[0.0, 0.0, 1.0, '1', '2'],
       [0.0, 1.0, 0.0, '3', '4'],
       [1.0, 0.0, 0.0, '5', '6']], dtype=object)